apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-manager-slack
  namespace: monitoring
  labels:
    alertmanagerConfig: global
spec:
  alertmanagerConfigMatcherStrategy:
    type: None
  route:
    group_by: ['namespace'] # ['job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'slack'
    routes:
    - receiver: 'null'
      match:
        alertname: DeadMansSwitch
    - receiver: 'slack'
      match:
      continue: true
  receivers:
  - name: 'slack'
    # Ref: https://docs.openshift.com/container-platform/4.12/rest_api/monitoring_apis/alertmanagerconfig-monitoring-coreos-com-v1beta1.html#spec-receivers-slackconfigs-apiurl
    slack_configs:
    - channel: '#alert-manager'
      apiURL:
        key: 'slack-webhook-url'
        name: 'alert-manager-slack-webhook-secret'
      send_resolved: true
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
      text: >-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
          *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
