apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../components/
- monitoring-ingress.yaml
- argocd-ingress.yaml
- argocd-notifications-cm.yaml
- sealed-argocd-notifications-secret.yaml
- trivy-alerts.yaml
- alert-manager-slack.yaml
- sealed-alertmanager-slack-webhook-secret.yaml

secretGenerator:
- name: argocd-notifications-secret
  namespace: argocd
  files:
  - sealed-argocd-notifications-secret.yaml
  options:
    annotations:
      config.kubernetes.io/local-config: "true"

- name: alertmanager-slack-webhook-secret
  namespace: monitoring
  files:
  - sealed-alertmanager-slack-webhook-secret.yaml
  options:
    annotations:
      config.kubernetes.io/local-config: "true"

configMapGenerator:
- name: custom-error-pages
  namespace: ingress-nginx-external
  files:
  - custom-error-pages/404.html
  - custom-error-pages/503.html

- name: trivy-operator-17813
  namespace: monitoring
  files:
  - dashboards/trivy-operator-17813.json
  options:
    # disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"

- name: external-ingress-14314
  namespace: ingress-nginx-external
  files:
  - dashboards/ingress-nginx-14314.json
  options:
    # disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"

- name: internal-ingress-14314
  namespace: ingress-nginx-internal
  files:
  - dashboards/ingress-nginx-14314.json
  options:
    # disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"

- name: cert-manager-20842
  namespace: cert-manager
  files:
  - dashboards/cert-manager-20842.json
  options:
    # disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"

- name: argocd-14584
  namespace: argocd
  files:
  - dashboards/argocd-14584.json
  options:
    # disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"

- name: loki-14055
  namespace: monitoring
  files:
  - dashboards/loki-14055.json
  options:
    # disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"
