---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgCoyst61Uo8Q3+x77bANF5D55aB9XCIisPN/R77JRCEaqvygh+8ZK8UDzMhRx1jKONTZ7/1gtgs0tN6dTzFnMvBF1EuScotkbNwQRUm3QDGvIOOFklWePvqa0qG3JN8AIgavDMW3AIHR94buOLPzD6UWNnc5YbDBTCuCE6eFhgO4xZYPZ0K7+07gioBfNGHGXYzP/xfd2zLwrc1jdQUdM6SzSTL758SrGfoSXcvcU+n8ghmhYBEhnq5ufL3qUn5YiKpGsRuP2jXVezNB0DrnBTL+T5Cte3RlllfhPZE1zwaoXfdknBICcoepXpbp5uisAHbxlqcQjNrl/fIiG+bnh0AfJBiZe8zSZY0l0GdlIRj8ykVoOu5O8WQHUyENel5l7FNq6zE9/m555u6x05qlx+t8fyn0yp4Cf6vNSff6WnPZ1ayegxXuJEAEfGsUgv34kZH9WTqbZqT9eAd4TM8gh4odKB45g47rDcqNDvUfcXqDQZilCHUbHVn2EIP6SjOmsa4bFkp4voUJRJrxTi3nVfJ8/yLQV++AaQtTh5GFkYyEIr7X67CEglkcyQ/dxeILRWrTNURRGILaqr499pnKteO8PuBI+G0KF1lbFd7bC3swY2uGBfxxMXTXF/CFDDccUJ07j7fUCRP+Z/nPclZawl9xUrNl2vsWW2sT8s/V837Rgmps3W0/Q3W1/9/E0gkCe6RIQK8lHbRgrBj8iUd3XD1U1G+l+Uogdt8IX31RBcIwaO7M3Z+ETRidXwhXjf2ZETj8r5qK1tFD+Q=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
