---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgA4gvI/xqIo2ukJoiiSAqh8cNsaNFi7vSWZ2B2Y25hYy8MNapk5gGUnJrln1qdAdayL2Rt43SbTdaj6PYnfj7689WhsN1lrbEmvzZDFcBTFsp5iJPAWoWBsL0YvJhechFzyrQ59L92a1jY1GzHjLJnfktFbSnXwl18/7exP6b03pZ5JS/mBCvTeRzosvP2Lf8TgyTgrluu3oaUvNWJE2kavKhKToE6f/6IlIWO2b/VB1+TpPUisJX9CCb+iY0KlUbeZIx/RgJXmaagF+K/G3mDh6Jz/xuYWA0pM0ebycdnsLgAMElFF9yCCjaGQSI7sqt9PMnEG3n8iT+wokeawa1OlPDmdpG88qRfar985LteaLJ6TG5IKsSK9tJU91gR1jME103v1Okp45qV1/ebhOgS/BbywK8M0y75vkMy2l49l/j3CYjbKF82yTiPxyRpvaJZbhOFd28AQaIhvRWfC9sje3zNWrDQZS/vUDYgbpWLdxLeglKYElQXARHKwCNAWM81FI+BUgvkngXSoGSxVcxtggQUZrsmSHUwatsc11hhc/wBFLfUbhYs8YnyZP8lOmxImUYqKH8HS2sjdgsgV5GCATSDQ6+OIdqVM3N9H13m+kucBA6KWh2fiJ90klioYeG9piDjm5DIFczOz392BsppIsaA914/8hnHdI3TrnOFgjfo2bfDHXZki8ScbsBUcqeft6OnyxkwbojSikTvI73PvCJdBP0KV4WFtiaa7pRq3TN5AflHk8f5mdFKlMinMAks3Ynd4qvVhZRM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
