apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-created.slack: alerts
    notifications.argoproj.io/subscribe.on-deleted.slack: alerts
    notifications.argoproj.io/subscribe.on-deployed.slack: alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-running.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: alerts
spec:
  project: default
  source:
    repoURL: https://github.com/ZiadMansourM/terraformed-odyssey.git
    targetRevision: HEAD
    path: ./kubernetes/test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
