apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ZiadMansourM/terraformed-odyssey.git
    targetRevision: HEAD
    path: ./kubernetes/voting-app/live
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
