apiVersion: v1
kind: Namespace
metadata:
  name: goviolin
---
apiVersion: v1
kind: Service
metadata:
  name: goviolin
  namespace: goviolin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: goviolin
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin
  namespace: goviolin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goviolin
  template:
    metadata:
      labels:
        app: goviolin
    spec:
      containers:
      - image: ziadmmh/goviolin:v0.0.1
        name: goviolin
        ports:
        - containerPort: 8080
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: goviolin-ingress-secret-cckm84f5k4
  namespace: goviolin
spec:
  encryptedData:
    auth: AgDRzmCn/vEQTQj5+qyIex/QKAiSVX+n4xTeu+hELEDscUX0YB1gm0WCHsT07rybOB3oz4L9umn5g61/UIWsPBxTKW4bS/5I36lGWJ6wbh1ZYXMJh9IaJ6pc0WX6adl7DxhtN0xB3WIqV7rAjHfBHkyUD4IY+MJ6NkMiYn4k0Rm0E1HpaQ8ag6RNKq5G2dEd+aoowENiymvtZ2oA5JSSJHHLW1lD1yXilnqijfH1beAjceUPlONselBrV1FE9fgNrP8vclJMvBgRp5+0lZFn2saBkiwbGCkd1K/yZcZiru2NtRe6hErm0gy1dbrHxoOfeYSCkztEkvXGL8ZZOnQ1bTVy0K3ZgAiUhwSVTyvbO3BJI4nVlWvt4q2aDaZCiUx7pG5k2HvMNqQRWy4lvtu8LgKM/7gPiC8bk7MHXffAXAIN/DH58wiiElmqLuaEVykll/Hx2k0QI/XVVv+m/kXTmXmAT4nfhFjb/q6cqPUiXUj4lLlRVG3noq2iCZjj5fCRFEq109aAhpl2woi7Bm150E8GuAFeYaXDfsyA2zzH5MSTWKFVVOXc1iijKuNF+YyESE6DfJ5JMmBKmq2ZzYzSbRHnrXOMyMrgELl6aS8i9ybrKvPNr8CpmuCHL8HrkZpZMIjN9rwhtCWNn8suz2e+RiwmsAvLHW0jlx+v6rnjq6pn3Cbhpx4whOnymCl8H3U6BawGcxt0sMIwrVREnJ2CGstLTwrNZBQuc18sWq+a7VUmHkKCP/eOzqC6wL7+Gw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: goviolin-ingress-secret-cckm84f5k4
      namespace: goviolin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01-production-cluster-issuer-public
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - GoViolin
    nginx.ingress.kubernetes.io/auth-secret: goviolin-external-ingress-passwd
    nginx.ingress.kubernetes.io/auth-type: basic
  name: goviolin
  namespace: goviolin
spec:
  ingressClassName: external-nginx
  rules:
  - host: goviolin.k8s.sreboy.com
    http:
      paths:
      - backend:
          service:
            name: goviolin
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - goviolin.k8s.sreboy.com
    secretName: goviolin-k8s-sreboy-com-key-pair
