apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-created.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-deleted.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-deployed.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-sync-running.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: root-app-alerts
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: root-app-alerts
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/ZiadMansourM/terraformed-odyssey.git
    targetRevision: HEAD
    path: ./argocd/app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
